version: "3"

services:
  sonarqube:
    image: sonarqube:lts
    platform: linux/x86_64
    environment:
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
    ports:
      - "9000:9000"
