spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:example@localhost:27017/}
      database: ${MONGO_DB_NAME:digital}
jwt:
  secretKey: ${JWT_SCRET_KEY:ecf1222c-88fd-47f3-988f-bdd78bade1ad}
server:
  port: 443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeme

elastic:
  hostname: 127.0.0.1
#  username: elastic
#  password: changeme

resilience4j:
  ratelimiter:
    instances:
      userService:
        limitForPeriod: 2
        limitRefreshPeriod: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true