version: '3.7'

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.40
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # Enable OTLP endpoint
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "14250:14250"  # OTLP gRPC
      - "14268:14268"  # Jaeger HTTP Thrift
      - "4318:4318"    # OTLP HTTP for traces
    depends_on:
      - elasticsearch
    networks:
      - jaeger-network

  jaeger-query:
    image: jaegertracing/jaeger-query:1.40
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "16686:16686"  # Jaeger UI
    depends_on:
      - jaeger-collector
    networks:
      - jaeger-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge
