apiVersion: v1
kind: Service
metadata:
  name: webflux-np-svc
spec:
  selector:
    name: webflux
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
