apiVersion: v1
kind: Service
metadata:
  name: webflux-service
  namespace: spring
spec:
  selector:
    app.kubernetes.io/name: webflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080