apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webflux-hpa
  namespace: spring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webflux
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40