apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-deployment
  namespace: spring
  labels:
    app: webflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webflux
  template:
    metadata:
      labels:
        app: webflux
        env: dev
    spec:
      containers:
        - name: webflux
          image: vijaypatidar31/webflux:latest
          platform: linux/x86_64
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: webflux-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 3
