apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-deployment
  namespace: spring
  labels:
    app: webflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webflux
  template:
    metadata:
      labels:
        app: webflux
    spec:
      containers:
        - name: webflux
          image: vijaypatidar31/webflux:1.1
          ports:
            - containerPort: 8080
        - name: elasticsearch
          image: elasticsearch:8.4.1
          environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
          networks:
            - es-net
          ports:
            - "9200:9200"
            - "9300:9300"
        - name: kibana
          image: kibana:8.4.1
          environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          networks:
            - es-net
          depends_on:
            - elasticsearch
          ports:
            - "5601:5601"

        - name: mongo
          image: mongo:6.0.1
          restart: always
          ports:
            - "27017:27017"
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
          volumes:
            - mongo:/data

        - name: redis
          image: redis:6.2-alpine
          restart: always
          ports:
            - '6379:6379'
          volumes:
            - redis:/data