apiVersion: v1
kind: Service
metadata:
  name: webflux-np-svc
  namespace: spring
spec:
  selector:
    app: webflux
  ports:
    - name: http
      port: 81
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
