apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webflux-hpa
  namespace: spring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webflux-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40